### PR TITLE
Remove dependency on window and document

### PR DESCRIPTION
**Pull request by jmorel**
I'm using this plugin in a React project and the server side rendering failed repeatedly because the plugin
requests the `window` and `document` variables.

Looking at the code, I saw that these variables were not used at all. I therefore removed them, which solved my issue with SSR.

I tried to update the dist folder but the diff got quite large (also updating the license for example). Do you want me to update it nonetheless?

### CODE REVIEW

**Comment by astanb** [comment]
Thanks for the help, fixed in latest release :]

**Comment by jmorel** [comment]
Thanks for putting out a new release so fast!

**Comment by jmorel** [comment]
Could you publish it to npm as well? I see only versions 0.0.1 and 0.0.4 there.

**Comment by astanb** [comment]
Done, sorry - forgot to publish to npm!

**Comment by jmorel** [comment]
No worries, the github release was already enough for my needs, this is just icing on the cake. Thanks a lot!

**Pull request closed without merging**
