### PR TITLE
Make it possible to use a function for axisTitle and update package.json.

### PR DESCRIPTION
**Pull request by SpaceK33z**
The `axisTitle` option now also accepts a function. The usecase for this is that when the data changes (e.g. via [`update()`](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-update), it's possible to change the axis title without completely re-rendering the chart.

I've also updated `package.json` to fix npm whining about a missing license and updated the dependencies.

### CODE REVIEW

**Comment by astanb** [comment]
Thanks for helping, I am really busy right now but will check this out when I have a chance during the next couple of days.

**Comment by SpaceK33z** [comment]
Oops, I also added the above commit to this PR. I can remove it if you don't agree with the changes I made in there.

**Comment by hansmaad** [comment]
We definitly need this, but this PR breaks existing code (it will break almost every application, since even the plugin name is changed). Can you remove unrelated changes to plugin name and options?

**Comment by astanb** [comment]
I have now implemented passing a function for axisTitle, as well as for axisClass

**Pull request closed without merging**
